### ISSUE TITLE
CI does not check for model functional regressions

### ISSUE THREAD

**Issue by sermazz** [gvsoc/gvsoc#43] opened 2024-06-27 15:43 UTC
In the CI, some software is run on the target models in the "Run examples" job. However, GVSOC does not propagate the return value. In other words, given a target, the CI job can only fail if the build of the model fails, or if there are issues in the binary loading. Functional correctness is never checked. See lines:
https://github.com/gvsoc/gvsoc/blob/main/.github/workflows/build.yml#L38-L45

The solution is either to propagate the return value of the software to GVSOC's returned status or, as an hotfix, to make the software print some value that can be parsed by the CI shell, as in https://github.com/gvsoc/gvsoc/pull/42/commits/5fc0b91d044722b1ee23fc7dfc342917f70aeb70. See line:
https://github.com/gvsoc/gvsoc/pull/42/commits/5fc0b91d044722b1ee23fc7dfc342917f70aeb70#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R47-R48

**Comment by haugoug** [comment] 2024-07-03 07:58
The return code is normally already returned from simulated SW to the shell.
I've just tested with axpy and it works well.
I compiled the snitch test with this option:
make OPENOCD_SEMIHOSTING=ON sw

**Comment by sermazz** [comment] 2024-07-09 14:09
To investigate this further I also tried one of the snitch_cluster tests (`fp32_computation_scalar`), also compiled with `make DEBUG=ON OPENOCD_SEMIHOSTING=ON sw`.
I added a printf of the return value before actually returning it. However, the return value that is returned by gvsoc simulation does not seem to depend on what the software returns.
You can check my CI logs here (on these branches I made the CI build and test only the snitch_cluster):
- https://github.com/sermazz/gvsoc/actions/runs/9858422797/job/27219749180#step:6:9
On this branch everything works, the simulation succeeds and 0 is returned by the software. However, gvsoc returns 1 and fails the CI.
- https://github.com/sermazz/gvsoc/actions/runs/9858455363/job/27219868300#step:6:9
On this branch, everything is the same, including the binary, but I injected a bug in the FP unit model. As you can see the number of errors is 3, which is the return value from the software. But the gvsoc return value is always 1 and does not change from the correct, baseline case.

**Comment by haugoug** [comment] 2024-07-12 09:17
Indeed there was a random issue, I didn't see it at first, thanks for reporting !
I think the issue is now fixed, can you update and try again ?

**Comment by sermazz** [comment] 2024-07-15 07:39
I tried again with the current upstream gvsoc main branch. The stdout is now different (`Input error: Platform returned an error (exitcode: 1)`, but the reported exitcode is always 1, for both the correct and wrong case (I tried the same example as before).

**Comment by haugoug** [comment] 2024-07-15 07:50
I cannot reproduce it, can you give me an elf file where you see the issue ?

**Comment by sermazz** [comment] 2024-07-15 08:12
Here is the same set up as before with your recent changes from upstream.
- Working snitch_cluster, should return 0:
https://github.com/sermazz/gvsoc/actions/runs/9935793332/job/27442673442#step:6:14
- snitch_cluster with broken flexfloat, should return an error:
https://github.com/sermazz/gvsoc/actions/runs/9935860102/job/27442876403#step:6:15

And again both return 1.
Find the binary (and the source code, compiled in the snitch_cluster repo with `DEBUG=ON OPENOCD_SEMIHOSTING=ON`) here:
https://github.com/sermazz/gvsoc/tree/smazzola/issue-43/examples/snitch_cluster

**Comment by haugoug** [comment] 2024-07-15 08:57
You're right I was working with a branch of snitch_cluster where I did a fix in the runtime for the exit.
There are other modifications in this branch blocking the merge.
I've pushed the fix in this branch, it should be merged soon to main: gvsoc_exit_fix

**Comment by sermazz** [comment] 2024-07-15 10:03
I see! So it was an issue in the Snitch runtime.
Thank you for the insights.
Maybe you can close this issue once the fix is merged :)

**Comment by haugoug** [comment] 2024-07-17 14:49
The fix has been merged, I close the issue, let me know if you still see anything wrong.

**Closed by haugoug** 2024-07-17 14:49 UTC

**Comment by haugoug** [comment] 2024-07-19 05:44
There was an issue with latest snitch cluster runtime which is now enqueuing 0 size transfer to idma.
I added the support to gvsoc idma model, now tests are working as before.
In case you see the issue, you can update gvsoc to latest version, I've just merged the fix.
